# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyarchon" do
  name "lazyarchon"
  desc "Terminal UI for Archon project management"
  homepage "https://github.com/yousfisaad/lazyarchon"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyarchon"

  on_macos do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-amd64.tar.gz"
      sha256 "62752fc0b5e20eb9a7cb71f88e83755098810fc84c4f70540a5b7715f13b7b0d"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-arm64.tar.gz"
      sha256 "09c26fe5332d60f64c1370d7cd07c1169ecc823e76cae0472be63a1ba7a8f099"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-amd64.tar.gz"
      sha256 "1839c24fa0eb2fb822f416a61296bf2fc0918a9f8a4a589aa8f86420d2829710"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-arm64.tar.gz"
      sha256 "a198742eef953f208336d2fb85aed5b2bc4c6fe26d3bce6a4204df867dc0a2a4"
    end
  end

  # No zap stanza required
end
