# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyarchon" do
  name "lazyarchon"
  desc "Terminal UI for Archon project management"
  homepage "https://github.com/yousfisaad/lazyarchon"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyarchon"

  on_macos do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-amd64.tar.gz"
      sha256 "0d7bd0c09df85b935a78ff11977ea18e16a51e25aa214d024acec65d0e691133"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-arm64.tar.gz"
      sha256 "680a2355130cc5efbe8231b9e3e2812249d7083dc7edd8b799f9367ba29d3d17"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-amd64.tar.gz"
      sha256 "36e65fd23a637bdb8480a7e62e4e8c0c16d0594bdd8dc438188a63d11c127c68"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-arm64.tar.gz"
      sha256 "e294e12665805de4460450b5f60fc70777a571af5f8c2778b2afe7194beead4e"
    end
  end

  # No zap stanza required
end
