# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyarchon" do
  name "lazyarchon"
  desc "Terminal UI for Archon project management"
  homepage "https://github.com/yousfisaad/lazyarchon"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyarchon"

  on_macos do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-amd64.tar.gz"
      sha256 "88405052f4fd776e39982f340d6b5c06060ca750446c1f80489dadcd002c32ab"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-darwin-arm64.tar.gz"
      sha256 "3f8d54b1957674414456cb9921013056f016523f202239e3f38b4c973ba72fbe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-amd64.tar.gz"
      sha256 "336b8afe2048ccd9a8395046fc41c2795842f819bee1ac7076604c11f99712b3"
    end
    on_arm do
      url "https://github.com/yousfisaad/lazyarchon/releases/download/v#{version}/lazyarchon-linux-arm64.tar.gz"
      sha256 "97bf8d34837ff91aeeb1ceac64b80482c54dc3d9cdab3543c2363bd11911e21d"
    end
  end

  # No zap stanza required
end
